name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload new files to Production folder on BunnyCDN using HTTP API
      run: |
        for file in $(find ./Webflow-CustomCode/ -type f); do
          echo "Uploading $file to BunnyCDN with Cache-Control header"
          curl -X PUT \
            --url "https://la.storage.bunnycdn.com/rooferscout-storagezone/Production/${file#./Webflow-CustomCode/}" \
            --header "AccessKey: ${{ secrets.BUNNY_API_KEY_STORAGE }}" \
            --header "Cache-Control: no-cache, no-store, must-revalidate" \
            --header "Content-Type: application/octet-stream" \
            --upload-file "$file" || exit 1;
        done

    - name: Purge BunnyCDN Cache for Updated Files
      run: |
        for file in $(find ./Webflow-CustomCode/ -type f); do
          PURGE_URL="https://api.bunny.net/purge?url=https%3A%2F%2FRooferScout-PullZone.b-cdn.net%2FProduction%2F${file#./Webflow-CustomCode/}&async=false"
          echo "Purging cache for $file"
          curl --request POST \
            --url "$PURGE_URL" \
            --header "AccessKey: ${{ secrets.BUNNY_API_KEY }}" || exit 1;
        done
