name: Deploy to BunnyCDN

on:
  push:
    branches:
      - main  # You can specify the branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload all files to BunnyCDN
      run: |
        find ./path/to/your/files/ -type f -exec curl -T {} ftp://storage.bunnycdn.com/your-storage-zone-name/{} --user ${{ secrets.BUNNY_API_KEY }}: \;
