name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload new files to Production folder on BunnyCDN using HTTP API
      run: |
        for file in $(find ./Webflow-CustomCode/ -type f); do
          echo "Uploading $file to BunnyCDN"
          curl -X PUT \
            --url "https://storage.bunnycdn.com/your_storage_zone/Production/${file#./Webflow-CustomCode/}" \
            --header "AccessKey: ${{ secrets.BUNNY_API_KEY }}" \
            --header "Content-Type: application/octet-stream" \
            --upload-file "$file" || exit 1;
        done
