name: Deploy to BunnyCDN

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload all files to BunnyCDN
      run: |
        for file in $(find ./Html-For-Webflow/ -type f); do
          curl -T $file ftp://la.storage.bunnycdn.com/${file#./Html-For-Webflow/} --user rooferscout-storagezone:${{ secrets.BUNNY_PASSWORD }};
        done
